name: connectivity_plus_platform_interface
description: A common platform interface for the connectivity_plus plugin.
version: 2.0.1
homepage: https://github.com/fluttercommunity/plus_plugins
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/
publish_to: none

environment:
  sdk: ">=3.3.4 <4.0.0"
  flutter: ">=3.19.4"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.11.0
  plugin_platform_interface:
    git: https://github.com/kumsumit/plugin_platform_interface.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
