name: connectivity_plus_platform_interface
description: A common platform interface for the connectivity_plus plugin.
version: 1.2.4
publish_to: none
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.9.1
  plugin_platform_interface:
    git: https://github.com/kumsumit/plugin_platform_interface.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 
    git: https://github.com/kumsumit/flutter_lints.git
